# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zj_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zj_Swift
    pod 'ShareCommon', :path => '../../ShareCommon'

  target 'zj_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'zj_SwiftUITests' do
    # Pods for testing
  end

end
